name: Docker release
on:
    push:
        tags:
            - "v[0-9]+.[0-9]+.[0-9]+"
permissions:
    packages: write
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - uses: docker/build-push-action@v4
              with:
                  push: true
                  context: .
                  file: gdynya/Dockerfile
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
