on: [push, pull_request]
jobs:
  rust-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy,rustfmt
      - uses: Swatinem/rust-cache@v2
      - run: cargo test --all-features
      - run: cargo fmt -- --check
      - run: cargo clippy --all-features -- -D warnings
  ui-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          cache: pnpm
          cache-dependency-path: gdynya-ui/pnpm-lock.yaml
      - run: pnpm install --frozen-lockfile
        working-directory: gdynya-ui
      - run: pnpm run lint
        working-directory: gdynya-ui
      - run: pnpm run build
        working-directory: gdynya-ui

